### ISSUE TITLE
Result should not come in an array

### ISSUE THREAD

**Issue by lferran** [guillotinaweb/guillotina_amqp#16]
Currently, responses for `@amqp-info/{task_id}` are:
```json
{
  "status": "finished",
  "updated": 1550497255.526748,
  "eventlog": [
    [
      "2019-02-18 13:41:16.961",
      {
        "members_count": 3,
        "completed": false
      }
    ],
    [
      "2019-02-18 13:41:16.963",
      {
        "members_count": 3,
        "completed": true
      }
    ]
  ],
  "job_data": {},
  "result": [
    {
      "members_count": 3,
      "completed": true
    }
  ]
}
```
Where the actual job result comes in a list with only one dict element.
We should probably make it just an outer dictionary (without the list) right? Would make it easier to parse

Unless there is a reason to keep it as a list, of course

**Comment by davidonna** [comment]
The job result comes as an array since we allowed the task to be either a coroutine or an asynchronous generator that can yield multiple results (in this case the yielded values are accumulated in the job result). If the task is a simple coroutine the job result is whatever the coroutine returns.

This means as of now it's up to the caller to determine what the result is by looking at the type which is not ideal.

**Comment by lferran** [comment]
we can keep it like this for now then
